#!/usr/bin/env node
import { writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { trainTgnn } from '../shared/tgnnTrain.js'

const root = dirname(fileURLToPath(import.meta.url))
const shared = join(root, '..', 'shared')

const checkpoint = trainTgnn({
  epochs: 20,
  graphsPerEpoch: 24,
  lr: 0.045,
  margin: 0.55,
  seed: 20260902,
  log: (msg) => console.log(msg),
})

const jsonPath = join(shared, 'tgnn_checkpoint.json')
writeFileSync(jsonPath, `${JSON.stringify(checkpoint, null, 2)}\n`)

const jsPath = join(shared, 'tgnn_checkpoint.js')
writeFileSync(
  jsPath,
  `/**
 * Trained TGNN weights. Regenerated by \`npm run train:tgnn\`.
 * Model file for Q&A: also see tgnn_checkpoint.json.
 */
export const TGNN_CHECKPOINT = ${JSON.stringify(checkpoint, null, 2)}
`
)

console.log(`wrote ${jsonPath}`)
console.log(`wrote ${jsPath} loss=${checkpoint.finalLoss}`)
