import {
  Activity,
  Anchor,
  Bell,
  Boxes,
  BrickWall,
  Building2,
  Bus,
  Camera,
  Car,
  Cloud,
  CloudRain,
  CloudSun,
  CloudUpload,
  Cpu,
  Database,
  Droplets,
  Fingerprint,
  Flame,
  Fuel,
  Globe,
  GraduationCap,
  HardDrive,
  HeartPulse,
  Home,
  Lamp,
  Landmark,
  Leaf,
  Library,
  Mail,
  Monitor,
  ParkingCircle,
  Plane,
  Radio,
  RadioTower,
  Router,
  Scale,
  Server,
  Shield,
  ShieldAlert,
  Siren,
  Skull,
  Store,
  Sun,
  Timer,
  TrafficCone,
  TrainFront,
  Trash2,
  Truck,
  Users,
  UtensilsCrossed,
  Waves,
  Wifi,
  WifiOff,
  Wind,
  Zap,
} from 'lucide-react'

/** Upper bound for normalizing load → green/red gradient in nodes and minimap */
export const MAX_PACKETS_PER_SECOND_FOR_VIS = 100_000

const HANDLES = {
  in: ['top', 'left', 'right', 'bottom'],
  out: ['top', 'left', 'right', 'bottom'],
}

function criticalityFromTrust(trust) {
  const t = Number(trust)
  if (!Number.isFinite(t)) return 'medium'
  if (t >= 90) return 'critical'
  if (t >= 75) return 'high'
  if (t >= 55) return 'medium'
  return 'low'
}

function sector({
  type,
  title,
  domain,
  Icon,
  pps,
  http,
  files = 0,
  logins = 0,
  trust,
  criticality,
}) {
  return {
    type,
    title,
    domain,
    defaultPacketsPerSecond: pps,
    defaultHttpRequestsPerMin: http,
    defaultFilesDownloaded: files,
    defaultFailedLoginsPerMin: logins,
    intrinsicTrust: trust,
    defaultCriticality: criticality ?? criticalityFromTrust(trust),
    Icon,
    handles: HANDLES,
  }
}

export const ASSET_DOMAINS = [
  'Energy',
  'Water',
  'Transportation',
  'Telecommunications',
  'Government',
  'Education',
  'Healthcare',
  'Emergency Services',
  'Public Safety',
  'Environment',
  'Finance',
  'Urban Infrastructure',
]

export const assetCatalog = [
  sector({
    type: 'power_grid',
    title: 'Power Grid',
    domain: 'Energy',
    Icon: Zap,
    pps: 28_000,
    http: 90,
    trust: 91,
  }),
  sector({
    type: 'power_substation',
    title: 'Power Substation',
    domain: 'Energy',
    Icon: Zap,
    pps: 16_000,
    http: 36,
    trust: 90,
  }),
  sector({
    type: 'renewable_energy',
    title: 'Renewable Energy',
    domain: 'Energy',
    Icon: Sun,
    pps: 14_000,
    http: 40,
    trust: 86,
  }),
  sector({
    type: 'fuel_energy_distribution',
    title: 'Fuel & Energy Distribution',
    domain: 'Energy',
    Icon: Fuel,
    pps: 11_000,
    http: 35,
    trust: 84,
  }),
  sector({
    type: 'natural_gas',
    title: 'Natural Gas Infrastructure',
    domain: 'Energy',
    Icon: Flame,
    pps: 9_500,
    http: 22,
    trust: 88,
  }),
  sector({
    type: 'ev_infrastructure',
    title: 'Electric Vehicle Infrastructure',
    domain: 'Energy',
    Icon: Car,
    pps: 7_200,
    http: 55,
    trust: 80,
  }),
  sector({
    type: 'water_supply',
    title: 'Water Supply',
    domain: 'Water',
    Icon: Droplets,
    pps: 12_000,
    http: 28,
    trust: 90,
  }),
  sector({
    type: 'wastewater_sewage',
    title: 'Wastewater & Sewage',
    domain: 'Water',
    Icon: Waves,
    pps: 8_400,
    http: 18,
    trust: 87,
  }),
  sector({
    type: 'flood_management',
    title: 'Flood Management',
    domain: 'Water',
    Icon: CloudRain,
    pps: 6_100,
    http: 24,
    trust: 85,
  }),
  sector({
    type: 'stormwater_management',
    title: 'Stormwater Management',
    domain: 'Water',
    Icon: CloudRain,
    pps: 5_400,
    http: 16,
    trust: 83,
  }),
  sector({
    type: 'waste_management',
    title: 'Waste Management',
    domain: 'Water',
    Icon: Trash2,
    pps: 4_800,
    http: 20,
    trust: 78,
  }),
  sector({
    type: 'traffic_management',
    title: 'Traffic Management',
    domain: 'Transportation',
    Icon: TrafficCone,
    pps: 16_000,
    http: 70,
    trust: 82,
  }),
  sector({
    type: 'public_transport',
    title: 'Public Transport',
    domain: 'Transportation',
    Icon: Bus,
    pps: 13_500,
    http: 95,
    trust: 81,
  }),
  sector({
    type: 'metro_rail',
    title: 'Metro & Rail',
    domain: 'Transportation',
    Icon: TrainFront,
    pps: 18_000,
    http: 110,
    trust: 88,
  }),
  sector({
    type: 'road_infrastructure',
    title: 'Road Infrastructure',
    domain: 'Transportation',
    Icon: TrafficCone,
    pps: 7_800,
    http: 25,
    trust: 79,
  }),
  sector({
    type: 'rail_infrastructure',
    title: 'Rail Infrastructure',
    domain: 'Transportation',
    Icon: TrainFront,
    pps: 9_200,
    http: 30,
    trust: 86,
  }),
  sector({
    type: 'airport_infrastructure',
    title: 'Airport Infrastructure',
    domain: 'Transportation',
    Icon: Plane,
    pps: 22_000,
    http: 180,
    files: 8,
    logins: 3,
    trust: 89,
  }),
  sector({
    type: 'port_maritime',
    title: 'Port & Maritime Infrastructure',
    domain: 'Transportation',
    Icon: Anchor,
    pps: 15_000,
    http: 85,
    files: 6,
    trust: 85,
  }),
  sector({
    type: 'parking_management',
    title: 'Parking Management',
    domain: 'Transportation',
    Icon: ParkingCircle,
    pps: 4_200,
    http: 40,
    trust: 74,
  }),
  sector({
    type: 'logistics_freight',
    title: 'Logistics & Freight',
    domain: 'Transportation',
    Icon: Truck,
    pps: 11_500,
    http: 75,
    files: 4,
    trust: 80,
  }),
  sector({
    type: 'telecommunications',
    title: 'Telecommunications',
    domain: 'Telecommunications',
    Icon: RadioTower,
    pps: 32_000,
    http: 160,
    trust: 92,
  }),
  sector({
    type: 'telecom_gateway',
    title: 'Telecom Gateway',
    domain: 'Telecommunications',
    Icon: Router,
    pps: 18_000,
    http: 80,
    trust: 91,
  }),
  sector({
    type: 'internet_infrastructure',
    title: 'Internet Infrastructure',
    domain: 'Telecommunications',
    Icon: Globe,
    pps: 30_000,
    http: 200,
    trust: 91,
  }),
  sector({
    type: 'public_wifi',
    title: 'Public Wi-Fi',
    domain: 'Telecommunications',
    Icon: Wifi,
    pps: 9_000,
    http: 48,
    logins: 6,
    trust: 68,
  }),
  sector({
    type: 'data_centers',
    title: 'Data Centers',
    domain: 'Telecommunications',
    Icon: Server,
    pps: 26_000,
    http: 140,
    files: 10,
    logins: 2,
    trust: 93,
  }),
  sector({
    type: 'cloud_digital',
    title: 'Cloud & Digital Infrastructure',
    domain: 'Telecommunications',
    Icon: Cloud,
    pps: 24_000,
    http: 220,
    files: 12,
    logins: 1,
    trust: 90,
  }),
  sector({
    type: 'identity_access',
    title: 'Identity & Access Infrastructure',
    domain: 'Telecommunications',
    Icon: Fingerprint,
    pps: 14_000,
    http: 260,
    logins: 8,
    trust: 94,
  }),
  sector({
    type: 'time_sync',
    title: 'Time & Synchronization Infrastructure',
    domain: 'Telecommunications',
    Icon: Timer,
    pps: 5_500,
    http: 12,
    trust: 95,
  }),
  sector({
    type: 'government_services',
    title: 'Government Services',
    domain: 'Government',
    Icon: Landmark,
    pps: 17_000,
    http: 150,
    files: 5,
    logins: 3,
    trust: 88,
  }),
  sector({
    type: 'citizen_services',
    title: 'Citizen Services',
    domain: 'Government',
    Icon: Users,
    pps: 10_500,
    http: 120,
    files: 3,
    logins: 2,
    trust: 82,
  }),
  sector({
    type: 'municipal_operations',
    title: 'Municipal Operations',
    domain: 'Government',
    Icon: Building2,
    pps: 8_800,
    http: 65,
    trust: 84,
  }),
  sector({
    type: 'public_housing',
    title: 'Public Housing',
    domain: 'Government',
    Icon: Home,
    pps: 6_400,
    http: 35,
    trust: 77,
  }),
  sector({
    type: 'education',
    title: 'Education',
    domain: 'Education',
    Icon: GraduationCap,
    pps: 9_600,
    http: 90,
    files: 14,
    trust: 80,
  }),
  sector({
    type: 'libraries_cultural',
    title: 'Libraries & Cultural Services',
    domain: 'Education',
    Icon: Library,
    pps: 4_100,
    http: 45,
    files: 9,
    trust: 81,
  }),
  sector({
    type: 'healthcare',
    title: 'Healthcare',
    domain: 'Healthcare',
    Icon: HeartPulse,
    pps: 19_000,
    http: 170,
    files: 7,
    logins: 4,
    trust: 92,
  }),
  sector({
    type: 'hospital_gateway',
    title: 'Hospital Gateway',
    domain: 'Healthcare',
    Icon: Router,
    pps: 11_000,
    http: 90,
    trust: 89,
  }),
  sector({
    type: 'hospital_auth',
    title: 'Hospital Auth',
    domain: 'Healthcare',
    Icon: Fingerprint,
    pps: 8_400,
    http: 210,
    logins: 6,
    trust: 93,
  }),
  sector({
    type: 'hospital_emr',
    title: 'Hospital EMR',
    domain: 'Healthcare',
    Icon: Database,
    pps: 14_000,
    http: 240,
    files: 18,
    logins: 5,
    trust: 94,
  }),
  sector({
    type: 'emergency_services',
    title: 'Emergency Services',
    domain: 'Emergency Services',
    Icon: Siren,
    pps: 14_500,
    http: 80,
    trust: 93,
  }),
  sector({
    type: 'police_services',
    title: 'Police Services',
    domain: 'Public Safety',
    Icon: Shield,
    pps: 12_800,
    http: 70,
    logins: 2,
    trust: 90,
  }),
  sector({
    type: 'fire_rescue',
    title: 'Fire & Rescue',
    domain: 'Emergency Services',
    Icon: Flame,
    pps: 8_200,
    http: 40,
    trust: 91,
  }),
  sector({
    type: 'surveillance_cctv',
    title: 'Surveillance & CCTV',
    domain: 'Public Safety',
    Icon: Camera,
    pps: 21_000,
    http: 30,
    files: 2,
    trust: 76,
  }),
  sector({
    type: 'public_safety_systems',
    title: 'Public Safety Systems',
    domain: 'Public Safety',
    Icon: ShieldAlert,
    pps: 11_000,
    http: 55,
    trust: 89,
  }),
  sector({
    type: 'disaster_management',
    title: 'Disaster Management',
    domain: 'Emergency Services',
    Icon: Siren,
    pps: 7_600,
    http: 42,
    trust: 88,
  }),
  sector({
    type: 'emergency_alert',
    title: 'Emergency Alert Systems',
    domain: 'Emergency Services',
    Icon: Bell,
    pps: 6_900,
    http: 38,
    trust: 94,
  }),
  sector({
    type: 'weather_services',
    title: 'Weather Services',
    domain: 'Environment',
    Icon: CloudSun,
    pps: 8_000,
    http: 36,
    trust: 87,
  }),
  sector({
    type: 'air_quality',
    title: 'Air Quality Monitoring',
    domain: 'Environment',
    Icon: Wind,
    pps: 3_800,
    http: 10,
    trust: 85,
  }),
  sector({
    type: 'environmental_monitoring',
    title: 'Environmental Monitoring',
    domain: 'Environment',
    Icon: Leaf,
    pps: 3_500,
    http: 8,
    trust: 84,
  }),
  sector({
    type: 'street_lighting',
    title: 'Street Lighting',
    domain: 'Environment',
    Icon: Lamp,
    pps: 5_200,
    http: 14,
    trust: 81,
  }),
  sector({
    type: 'banking_financial',
    title: 'Banking & Financial Services',
    domain: 'Finance',
    Icon: Landmark,
    pps: 23_000,
    http: 320,
    files: 6,
    logins: 5,
    trust: 94,
  }),
  sector({
    type: 'retail_infrastructure',
    title: 'Retail Infrastructure',
    domain: 'Finance',
    Icon: Store,
    pps: 12_200,
    http: 140,
    files: 3,
    logins: 2,
    trust: 78,
  }),
  sector({
    type: 'food_supply',
    title: 'Food Supply Infrastructure',
    domain: 'Urban Infrastructure',
    Icon: UtensilsCrossed,
    pps: 9_400,
    http: 50,
    trust: 83,
  }),
  sector({
    type: 'supply_chain',
    title: 'Supply Chain Infrastructure',
    domain: 'Finance',
    Icon: Boxes,
    pps: 13_000,
    http: 85,
    files: 5,
    trust: 82,
  }),
  sector({
    type: 'postal_delivery',
    title: 'Postal & Delivery Services',
    domain: 'Finance',
    Icon: Mail,
    pps: 7_100,
    http: 60,
    trust: 79,
  }),
  sector({
    type: 'urban_infrastructure',
    title: 'Urban Infrastructure',
    domain: 'Urban Infrastructure',
    Icon: BrickWall,
    pps: 10_000,
    http: 44,
    trust: 80,
  }),
]

/** Previous IoT catalog — kept so saved rooms and imports still render. */
export const legacyAssetCatalog = [
  sector({
    type: 'env_sensor',
    title: 'Environmental sensor',
    domain: 'Environment',
    Icon: Radio,
    pps: 3_500,
    http: 6,
    trust: 58,
  }),
  sector({
    type: 'smart_actuator',
    title: 'Smart actuator',
    domain: 'Energy',
    Icon: Zap,
    pps: 2_000,
    http: 4,
    trust: 72,
  }),
  sector({
    type: 'edge_gateway',
    title: 'Edge gateway',
    domain: 'Telecommunications',
    Icon: Router,
    pps: 12_000,
    http: 45,
    files: 2,
    trust: 88,
  }),
  sector({
    type: 'ip_camera',
    title: 'IP camera',
    domain: 'Public Safety',
    Icon: Camera,
    pps: 9_000,
    http: 12,
    files: 1,
    trust: 70,
  }),
  sector({
    type: 'wearables_hub',
    title: 'Wearables hub',
    domain: 'Healthcare',
    Icon: Activity,
    pps: 6_500,
    http: 18,
    trust: 65,
  }),
  sector({
    type: 'plc_controller',
    title: 'Industrial PLC',
    domain: 'Energy',
    Icon: Cpu,
    pps: 4_500,
    http: 8,
    trust: 82,
  }),
  sector({
    type: 'cloud_ingest',
    title: 'Cloud ingest',
    domain: 'Telecommunications',
    Icon: CloudUpload,
    pps: 18_000,
    http: 220,
    files: 12,
    logins: 1,
    trust: 90,
  }),
  sector({
    type: 'mqtt_broker',
    title: 'MQTT broker',
    domain: 'Telecommunications',
    Icon: Server,
    pps: 15_000,
    http: 60,
    trust: 85,
  }),
  sector({
    type: 'app_server',
    title: 'Application server',
    domain: 'Telecommunications',
    Icon: Monitor,
    pps: 22_000,
    http: 480,
    files: 8,
    logins: 2,
    trust: 86,
  }),
  sector({
    type: 'database_server',
    title: 'Database server',
    domain: 'Telecommunications',
    Icon: Database,
    pps: 12_000,
    http: 140,
    files: 4,
    logins: 3,
    trust: 92,
  }),
  sector({
    type: 'api_gateway',
    title: 'API gateway',
    domain: 'Telecommunications',
    Icon: Globe,
    pps: 25_000,
    http: 480,
    files: 6,
    logins: 4,
    trust: 88,
  }),
  sector({
    type: 'load_balancer',
    title: 'Load balancer',
    domain: 'Telecommunications',
    Icon: Scale,
    pps: 30_000,
    http: 320,
    logins: 1,
    trust: 90,
  }),
  sector({
    type: 'firewall',
    title: 'Firewall',
    domain: 'Telecommunications',
    Icon: Shield,
    pps: 28_000,
    http: 180,
    logins: 2,
    trust: 94,
  }),
  sector({
    type: 'object_storage',
    title: 'Object storage',
    domain: 'Telecommunications',
    Icon: HardDrive,
    pps: 16_000,
    http: 90,
    files: 24,
    logins: 1,
    trust: 89,
  }),
]

export const attackCatalog = [
  {
    type: 'rogue_sensor',
    title: 'Rogue sensor',
    domain: 'Public Safety',
    defaultPacketsPerSecond: 8_000,
    defaultHttpRequestsPerMin: 120,
    defaultFilesDownloaded: 0,
    defaultFailedLoginsPerMin: 0,
    intrinsicTrust: 18,
    defaultCriticality: 'low',
    Icon: Skull,
    handles: HANDLES,
    provenance: 'injected',
  },
  {
    type: 'rogue_gateway',
    title: 'Rogue gateway',
    domain: 'Telecommunications',
    defaultPacketsPerSecond: 22_000,
    defaultHttpRequestsPerMin: 600,
    defaultFilesDownloaded: 0,
    defaultFailedLoginsPerMin: 0,
    intrinsicTrust: 22,
    defaultCriticality: 'low',
    Icon: WifiOff,
    handles: HANDLES,
    provenance: 'injected',
  },
]

const allAssets = [...assetCatalog, ...legacyAssetCatalog, ...attackCatalog]
const assetsByType = new Map(allAssets.map((a) => [a.type, a]))

export function getAssetByType(type) {
  return assetsByType.get(type)
}

export function getAssetsGroupedByDomain() {
  const groups = ASSET_DOMAINS.map((domain) => ({
    domain,
    assets: assetCatalog.filter((a) => a.domain === domain),
  }))
  return groups.filter((g) => g.assets.length > 0)
}
